# Generated by Django 5.2.14 on 2026-05-24 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['level', 'time_ms', 'created_at'], name='game_score_level_i_c8c9bb_idx'),
        ),
    ]
